### ISSUE TITLE
Improve external popup menu appearance

### ISSUE THREAD

**Issue by clason** [smolck/uivonim#10]
- [x] In the TUI, word and menu are printed in separate columns; would be nice to have this for the external menu as well.
- [x] Menu only shows a subset of entries but does not scroll if end is reached.
- [x] Single-character completion items are shown as numbers (their ASCII char codes) instead
~~- [ ] Support base64-encoded images in Markdown for the documentation window~~ EDIT(smolck): Not sure how many LSPs (if any?) support this so'll leave it for now.
- [ ] Re-enable word-wrapping for multi-line pum (`menu`) entries, with consistent alignment of all cells (either centered or -- better? -- top-aligned)

**Comment by romgrk** [comment]
One more thing: in the TUI, completion text is aligned with the input text. It would be nice if the popup could do the same in uivonim.

Actual:
![Screenshot from 2020-10-30 16-03-42](https://user-images.githubusercontent.com/1423607/97752113-cc1af700-1ac9-11eb-9f7c-52e7320dacb7.png)

Expected:
![Screenshot from 2020-10-30 16-05-35](https://user-images.githubusercontent.com/1423607/97752127-d0dfab00-1ac9-11eb-8e4a-ea8cf7b3fee2.png)

**Comment by smolck** [comment]
@romgrk Should be fixed in https://github.com/smolck/uivonim/commit/6aee29e75671cbc0a67e3ac2faaa0adc4cc3db9e, although I'm not sure about how that ends up looking for smaller window sizes.

**Comment by romgrk** [comment]
One more thing: the popup menu doesn't seem to be respecting `Pmenu` colors.

**Comment by smolck** [comment]
> One more thing: the popup menu doesn't seem to be respecting `Pmenu` colors.

This is actually a broader issue due to uivonim kind of doing it's own thing for the colors of external UI elements. I'll see if I can get a PR that fixes this for all UI elements.

**Comment by smolck** [comment]
>     * [x]  In the TUI, word and menu are printed in separate columns; would be nice to have this for the external menu as well.
> 
>     * [x]  Menu only shows a subset of entries but does not scroll if end is reached.
> 
>     * [ ]  Single-character completion items are shown as numbers (their ASCII char codes) instead
> 
>     * [ ]  Support base64-encoded images in Markdown for the documentation window
> 
>     * [ ]  Re-enable word-wrapping for multi-line pum (`menu`) entries, with consistent alignment of all cells (either centered or -- better? -- top-aligned)

@clason I think (3) is no longer an issue now that we use node-client, (4) I need a test case for but would theoretically be pretty straightforward to add; also need a test case for that last one if you wouldn't mind, and mind elaborating a bit on what exactly you mean with that one too? Been a while since I worked on the pmenu-related code so don't really remember what that one's about 😅
