### ISSUE TITLE
Cursor jumps in terminal

### ISSUE THREAD

**Issue by clason** [smolck/uivonim#14]
When typing in a `:terminal` buffer, the cursor jumps back to a previous character on every keystroke (including cursor movement and backspace).

**Comment by romgrk** [comment]
I've seen it happen in other UIs as well. Normally with the new grid implementation neovim is supposed to separate cursor-movement and drawing-pen-movement events. I wonder if they forgot to do it here.

**Comment by smolck** [comment]
Doesn't appear to be an issue anymore from some quick testing; closing.
