### ISSUE TITLE
Impossible to type "<"

### ISSUE THREAD

**Issue by Guardian-Spirit** [smolck/uivonim#207]
Using Manjaro Architect build. Installation from YAY (uivonim-git package).

Impossible to type "<" symbol in INSERT mode. ">", on the other hand, works fine. Regular console `neovim` works fine with "<". No plugins and no additional configuration provided in `init.vim`.

**Comment by smolck** [comment]
Thanks for the issue, I somehow hadn't noticed this 😅 I'll look into it, sounds like a really weird bug . . .

**Comment by smolck** [comment]
Turns out this wasn't so weird after all, from `:help nvim_input()`:

```
Note:
    |keycodes| like <CR> are translated, so "<" is special. To
    input a literal "<", send <LT>.
```

So just had to replace `<` with `<LT>` whenever `<` is the only char inputted.
