### ISSUE TITLE
Float windows not cleared from screen after closing

### ISSUE THREAD

**Issue by romgrk** [smolck/uivonim#41]
Float windows are drawn on screen even after closing.

![Screenshot from 2020-10-30 17-26-13](https://user-images.githubusercontent.com/1423607/97758390-24a3c180-1ad5-11eb-914e-ccb42cbd4c6a.png)

**Comment by smolck** [comment]
I'm fairly certain this was introduced with https://github.com/smolck/uivonim/commit/bce7508121605011b781a704e3dcb74f39e7480d, I noticed it the other day, but have yet to come up with a fix for it. Having to run `windows.layout()` on grid_flush is pretty expensive, and caused a ton of lag in visual mode.
