### ISSUE TITLE
Cursor character not looking ok

### ISSUE THREAD

**Issue by romgrk** [smolck/uivonim#42]
The cursor character doesn't use the same font as the editor therefore it doesn't display characters the same way. Also it's not positioned correctly.

![Screenshot from 2020-10-31 23-29-04](https://user-images.githubusercontent.com/1423607/97794465-e5f33180-1bd0-11eb-836c-3075e11a888e.png)

**Comment by smolck** [comment]
From https://github.com/smolck/uivonim/issues/40#issuecomment-719969514:

> The cursor char is rendered as a HTML/DOM node. It's a z-index thing because I was too lazy to implement the cursor in WebGL.

I guess the proper solution is to implement this in WebGL then, but that might take a good bit of work; a faster fix is probably to just change a few CSS props on the cursor div/span.

**Comment by smolck** [comment]
So, bit of a status report; drawing just the cursor block with webgl is fairly trivial (which I've done in #44), you just change the background color of the current cell (doesn't quite work with multiple windows though, but hopefully soon). However, I don't really know how to go about drawing the other cursor cursor shapes, specifically the line shape.
