### ISSUE TITLE
MacOS: A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by shaunsingh** [smolck/uivonim#453]
![image](https://user-images.githubusercontent.com/71196912/139352255-5fc8a7d2-d727-421f-a124-9db6d258a6ce.png)

Built on M1 (macOS, arm64). Latest NPM/Yarn. Just cloned it today, built from master with `npm ci` then `npm run package`

**Comment by Pritep** [comment]
Me too, but on Linux.

**Comment by adenosinetp10** [comment]
I get the same error and I'm on windows 10 22H2.
