### ISSUE TITLE
Package for Arch Linux is available

### ISSUE THREAD

**Issue by SilverRainZ** [smolck/uivonim#55]
Hello smolck, thanks for your contribution to such an awesome project!

I made a package script for ArchLinux and upload it to [AUR](https://aur.archlinux.org/packages/uivonim-git/), just a notify, nothing else :-), B.T.W. I will add it to @archlinuxcn soon.

**Comment by smolck** [comment]
Thank you so much! I really appreciate it!

One question I have is regarding adding a `.desktop` file; is there anything specific I need to do to get that to work with the AUR package so uivonim shows up as an app after install, or will the package need to be updated after I add the desktop file to make that work?

Thanks again for doing this!

**Comment by SilverRainZ** [comment]
I will write a simple desktop file for this package :-)

**Comment by SilverRainZ** [comment]
Hi, I wrote a desktop entry[1] for uivonim.

[1] https://aur.archlinux.org/cgit/aur.git/tree/uivonim.desktop?h=uivonim-git

**Comment by SilverRainZ** [comment]
BTW, uivonim binary package is available in [archlinuxcn] community repository[1].

[1] https://github.com/archlinuxcn/repo/commit/cec41059cda16ad0c037ff4df109e8c58988eef6
