### ISSUE TITLE
Highlighting inconsistency/flickering

### ISSUE THREAD

**Issue by smolck** [smolck/uivonim#6]
ATM highlighting is pretty broken, where colors can be changing all the time, change underneath the cursor; overall they just don't render correctly (except for `:colorscheme veonim`?). It seems dependent on the colorscheme, but I'm not sure of the exact cause. Removing the colorizer (`src/workers/neovim-colorizer.ts`) didn't fix it apparently, nor did commenting out most of `src/services/colorizer.ts` (which was/is a temporary fix for some errors leftover from the colorizer remove).

**Comment by clason** [comment]
Note: I don't see any of this on macOS, so this looks to be a low-level (electron or webGL) issue.

**Comment by breja** [comment]
On Linux I had issues making the color atlas texture lookups work correctly. It seems like the x, y coordinates end up picking values from adjacent cells and so the colors are wrong.

What I did to fix it (hopefully) is to make the color atlas texture "cells" bigger than 1x1 so even if the x,y coordinates are slightly off, the right color is chosen. I'm sure there's some reason for this madness, but I'm a WebGL noob, and debugging WebGL is hard.

This seems to work for me on Linux and MacOS. Maybe it will work for you as well?

#### render/highlight-attributes.ts

```diff
export const generateColorLookupAtlas = () => {
   const max = Math.max(...highlights.keys(instances.current))
-  canvas.width = max + 1
-  canvas.height = 3
+  const texelSize = 2
+  canvas.width = (max + 1) * texelSize
+  canvas.height = 3 * texelSize

   const defaultColors = getCurrentDefaultColors()
   ui.imageSmoothingEnabled = false

   highlights.forEach(instances.current, (hlgrp, id) => {
     const defbg = hlgrp.reverse
       ? defaultColors.foreground
       : defaultColors.background
     ui.fillStyle = hlgrp.background || defbg
-    ui.fillRect(id, 0, 1, 1)
+    ui.fillRect(id * texelSize, 0, texelSize, texelSize)

     const deffg = hlgrp.reverse
       ? defaultColors.background
       : defaultColors.foreground
     ui.fillStyle = hlgrp.foreground || deffg
-    ui.fillRect(id, 1, 1, 1)
+    ui.fillRect(id * texelSize, 1 * texelSize, texelSize, texelSize)

     if (!hlgrp.underline) return

     const color = hlgrp.special || defaultColors.special
     ui.fillStyle = color
-    ui.fillRect(id, 2, 1, 1)
+    ui.fillRect(id * texelSize, 2 * texelSize, texelSize, texelSize)
  })

  return canvas
}
```

#### render/webgl-text-bg.ts

```diff
-      vec2 colorPosition = vec2(${v.hlid} + 0.0001, ${v.hlidType} + 0.0001) / ${v.colorAtlasReso
  lution};
+      float texelSize = 2.0;
+      float color_x = ${v.hlid} * texelSize + 1.0;
+      float color_y = ${v.hlidType} * texelSize + 1.0;
+
+      vec2 colorPosition = vec2(color_x, color_y) / ${v.colorAtlasResolution};
```

#### render/webgl-text-fg.ts

```diff
-      vec2 colorPosition = vec2(${v.hlid} + 0.0001, 1.0001) / ${v.colorAtlasResolution};
+      float texelSize = 2.0;
+      float color_x = ${v.hlid} * texelSize + 1.0;
+      float color_y = 1.0 * texelSize + 1.0;
+
+      vec2 colorPosition = vec2(color_x, color_y) / ${v.colorAtlasResolution};
```

By the way, great work on the project! I think using the builtin LSP support is a great idea. It's nice to see that the neovim devs considered both terminal and graphical UIs for the LSP support.

Apologies for my messy experimental code - never expected someone else to pick it up. There is a lot of rubbish that can be disposed of 😄 

If you have any questions about anything let me know.

**Comment by smolck** [comment]
Great, that works @breja! Thank you so much! I've pushed it to a separate branch that will hopefully be merged soon (assuming I get things working & I figure out the security issue with it).

> Apologies for my messy experimental code - never expected someone else to pick it up. There is a lot of rubbish that can be disposed of :smile:

No worries! I'm learning a good bit working on it, and it's proving to be a cool project to work on ;) Thanks for starting Veonim in the first place!

> If you have any questions about anything let me know.

Will do, thank you! One thing I have wondered about is why you archived the original project? If you don't wish to share that, no worries, I'm just curious.

**Comment by breja** [comment]
> Will do, thank you! One thing I have wondered about is why you archived the original project? If you don't wish to share that, no worries, I'm just curious.

I burned out while working on the project, and did not have the energy to continue. I suppose I could have asked for maintainers to take over, but I didn't think anyone would be interested.
