### ISSUE TITLE
Update current directory on opening files

### ISSUE THREAD

**Issue by clason** [smolck/uivonim#9]
The builtin statusline has indicators for git branches and changes, but these are based on the current directory, not the directory of the currently opened file. (To see this, start veonim from its own repo and then `:e dir/file` -- the repo is still uivonim's; you explicitly need to `:cd dir` to update the git information.)

**Comment by smolck** [comment]
Any reason this can't be fixed via a simple `nvim.command('cd dir')` or similar whenever a new directory is opened, or perhaps by a neovim option to do the same? Or should this be handled differently (I haven't looked into the code that provides the git information, so maybe there's a different way of finding the directory that should be used instead)?

**Comment by clason** [comment]
I don't think that's how nvim behaves -- the `cwd` remains set to the directory on startup, but statusline components are of course related to the current buffer. It's just that the Uivonim components do not behave the same (i.e., do not adapt to changes of the buffer). So it's an issue only on the Uivonim side, I think.

**Comment by smolck** [comment]
Ah, okay. So just need to get the directory based on the current file (or the root folder of the current file, i.e. where the `.git` directory is) and not using the `cwd`. Perhaps there is a plugin somewhere that has an implementation of this which could show how to do this properly?

**Comment by smolck** [comment]
Unless I'm misunderstanding, it seems this was fixed at some point; it worked on master pre-#191, and as of https://github.com/smolck/uivonim/commit/7eb67ff774c14ed0ab5a25d3c7c7fc6da01b1f7e it now works again. Closing.
