### ISSUE TITLE
Zoom in and out

### ISSUE THREAD

**Issue by Bhanukamax** [smolck/uivonim#95]
Hi, is there a way to zoom in and out? like `Ctrl +` and `Ctrl -` or `Ctrl Shift -` which is the usually behavior on terminal or even in most `GUI` editors.

**Comment by smolck** [comment]
Hello! By “zoom in and out” do you mean increase/decrease the font size, or focus in/out on a specific part of the editor?

**Comment by Bhanukamax** [comment]
Hi @smolck thanks for the swift reply. By zoom I meant zooming in out the entire UI, this is something I use a lot with neovim. It makes  it easy to zoom in and out when required, without resetting the font sizes.
Please let me if there's any suggested work around for this for now, because I'm really exited to test `uivonim` out.

I'll paste few gifs here to show what I mean:

This is the zoom in and out in neovim running  on the terminal:
![neovim-term-zoom](https://user-images.githubusercontent.com/8494781/103461449-78848e00-4d44-11eb-9df2-19bbf755e358.gif)


This is the `Oni2` gui doing the same:
![oni2-zoom](https://user-images.githubusercontent.com/8494781/103461470-9651f300-4d44-11eb-91c3-7ca21cf4051c.gif)

**Comment by Bhanukamax** [comment]
as a quick work around I started setting the `guifont` size manually when i need to adjust

**Comment by smolck** [comment]
As of https://github.com/smolck/uivonim/commit/4028373b43fa26e0cfa47a67d13352a3155a48b7 this functionality now is enabled by default and done via `Ctrl shift +` and `Ctrl shift -`. Note that you can now also register shortcuts for uivonim to handle, thus allowing for `Ctrl shift` mappings which aren't usually possible in the terminal. Here's an example showcasing the new configuration options:

```lua
-- init.lua
if vim.g.uivonim == 1 then
  vim.defer_fn(function()

    -- Assumes SomeOtherCommandToRun and HurrayForControlShiftMappings are defined somewhere
    require'uivonim'.register_shortcuts {
      { '<C-S-P>', ':echo "Hello, World!"' },
      { '<C-S-Y>', ':SomeOtherCommandToRun' },
      { '<C-S-N', ':call HurrayForControlShiftMappings()' },
    }

    -- Can also unregister shortcuts
    require'uivonim'.unregister_shortcuts { '<C-S-P>' } -- No more echoing "Hello, World!" on ctrl+shift+p

    -- Don't like the default mappings?
    require'uivonim'.disable_default_shortcuts()

    -- Want them back?
    require'uivonim'.enable_default_shortcuts()
  end, 1000)
end
```
